# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: archlinux/base

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install Required Packages
        run: pacman -Syy --noconfirm --noprogressbar tar git
        
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Update System
        run: pacman -Syyuu --noprogressbar --noconfirm

      # Runs a set of commands using the runners shell
      - name: Install Required Python related packages
        run: |
          pacman -Sy --noconfirm --noprogressbar python{,-pip} tk gcc
          pip install poetry
          poetry config virtualenvs.in-project true
          poetry install
          source .venv/bin/activate
          poetry build
